apiVersion: v1
kind: Service
metadata:
  name: my_namespace_flask
spec:
  selector:
    app: my_namespace_flask
  ports:
    - port: 5000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_namespace_flask
  labels:
    apps: my_namespace_flask
spec:
  selector:
    matchLabels:
      app: my_namespace_flask
  replicas: 1
  template:
    metadata:
      labels:
        app: my_namespace_flask
    spec:
      containers:
        - name: my_namespace_flask
          image: icr.io/my_namespace_flask/app:latest
          # image: eu-de.icr.io/my_namespace_flask/app:latest
          ports:
            - containerPort: 5000
